### ISSUE TITLE
Occasional bug on color_set

### ISSUE THREAD

**Issue by Keis0n** [Submoon/MyMan#21]
Sometimes when the function creates a role for the user, the first setRolePosition doesn't update the bot's role position. It happens rarely, and using color_del and color_set should solve the problem.

**Comment by Submoon** [comment]
First try in pull request #23 .
This is not enough apparently. Looks like there is a bug on the discord API side?

**Comment by Ekelz** [comment]
Modified the way we're updating by adding an explicit promise.
Waiting for more tests to confirm the fix.

**Comment by Submoon** [comment]
Looks like it's corrected in PR #39 .
Waiting for tests on the production bot to confirm.
